software_groups: &software
  - "base"

packages:
  branch_codenames:
    master: trusty-unstable
    production: trusty-stable

jobs:
  roger:
    builder: "golang"
    base: "quay.io/madebymany/build-bases:trusty"
    packages:
      - type: debian
        name: roger
        depends:
          - libc6
        target: install
        repos:
          - composed-public
        activates:
          - roger-upgrade
