software_groups: &software
  - "base"
jobs:
  roger:
    builder: "golang"
    base: "ubuntu:12.04"
    software_groups: *software
    packages:
      - type: debian
        name: roger
        depends:
          - libc6
        target: install
        repos:
          - mxm-public
